language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - TEST_COMMAND="composer test"
    matrix:
        - SYMFONY_VERSION=3.0.*
        - SYMFONY_VERSION=2.8.*
        - SYMFONY_VERSION=2.7.*

branches:
    except:
        - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
        # Test stable versions
        - php: 5.4
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 5.5
        - php: 5.6
        - php: 7.0
          env: COVERAGE=true TEST_COMMAND="composer test-ci" DEPENDENCIES="symfony/symfony:2.7.* henrikbjorn/phpspec-code-coverage:^1.0"

        # Test LTS versions:
        - php: 7.1
          env: DEPENDENCIES="symfony/lts:^2"
        - php: 7.1
          env: DEPENDENCIES="symfony/lts:^3"

        # Test development versions
        - php: 7.1
          env: DEPENDENCIES="dev"

        # Test alternative runtimes:
        - php: hhvm

    allow_failures:
        - env: DEPENDENCIES="dev"

before_install:
    - travis_retry composer self-update
    - if [ "$STABILITY" != "" ]; then composer config minimum-stability $STABILITY; fi;
    - if [ "$DEPENDENCIES" != "" ]; then composer require --no-update $DEPENDENCIES; fi

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - composer validate --strict --no-check-lock
    - $TEST_COMMAND

after_success:
    - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
