language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - TEST_COMMAND="composer test"
    matrix:
        - SYMFONY_VERSION=3.0.*
        - SYMFONY_VERSION=2.8.*
        - SYMFONY_VERSION=2.7.*

branches:
    except:
        - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
        - php: 5.4
          env: DEPENDENCIES=minimum COVERAGE=true TEST_COMMAND="composer test-ci" SYMFONY_VERSION=2.7.*
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
          env: DEPENDENCIES="symfony/lts:^3"
        - php: 7.1
          env: DEPENDENCIES="dev" SYMFONY_VERSION=4.0.*
        - php: hhvm
    allow_failures:
        - php: 7.1
          env: DEPENDENCIES="dev" SYMFONY_VERSION=4.0.*

before_install:
    - travis_retry composer self-update
    - if [ "$DEPENDENCIES" = "minimum" ]; then COMPOSER_FLAGS="--prefer-stable --prefer-lowest"; fi;
    - if [ "$DEPENDENCIES" = "dev" ]; then composer config minimum-stability dev; fi;
    - if [[ $DEPENDENCIES == *"/"* ]]; then composer require --no-update $DEPENDENCIES; fi;

install:
    - travis_retry composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - composer validate --strict --no-check-lock
    - $TEST_COMMAND

after_success:
    - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
